package artvalleysystem;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class AddArtWork extends javax.swing.JFrame {
    String phonenumber,picPath="";
    public AddArtWork(String p ) {
        super("Add Art ");
        initComponents();
         phonenumber=p;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Type = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();
        TextMaterial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PriceText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DesText = new javax.swing.JTextArea();
        YearText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ArtText = new javax.swing.JTextField();
        Rpating = new javax.swing.JRadioButton();
        jSculpture = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        QuantityComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HightText = new javax.swing.JTextField();
        WidhthText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ImageIconLabel = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        exitButton2 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        exitButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 89, 146), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 89, 146));
        jLabel4.setText("Material");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 144, 27));

        UploadButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UploadButton.setForeground(new java.awt.Color(17, 89, 146));
        UploadButton.setText("Upload");
        UploadButton.setToolTipText("");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 120, 30));

        TextMaterial.setText("Enter sculpture material  here");
        jPanel1.add(TextMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 302, 34));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 89, 146));
        jLabel2.setText("Price:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 144, 27));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 89, 146));
        jLabel5.setText("Type of art: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 124, 27));

        PriceText.setText("Enter price here");
        PriceText.setMinimumSize(new java.awt.Dimension(10, 34));
        PriceText.setPreferredSize(new java.awt.Dimension(80, 34));
        jPanel1.add(PriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 302, -1));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Add Artwork");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 54));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(17, 89, 146));
        jLabel10.setText("Add picture:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, 27));

        DesText.setColumns(20);
        DesText.setRows(5);
        DesText.setText("describe  your Art");
        jScrollPane2.setViewportView(DesText);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 300, -1));

        YearText.setText("Enter year of art here");
        YearText.setMinimumSize(new java.awt.Dimension(10, 34));
        YearText.setPreferredSize(new java.awt.Dimension(80, 34));
        jPanel1.add(YearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 302, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(17, 89, 146));
        jLabel15.setText("Art name:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 144, 27));

        ArtText.setText("Enter art name ");
        jPanel1.add(ArtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 302, 34));

        Rpating.setBackground(new java.awt.Color(255, 255, 255));
        Type.add(Rpating);
        Rpating.setText("Paint");
        Rpating.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeItemStateChanged(evt);
            }
        });
        jPanel1.add(Rpating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jSculpture.setBackground(new java.awt.Color(255, 255, 255));
        Type.add(jSculpture);
        jSculpture.setText("Sculpture");
        jSculpture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TypeItemStateChanged(evt);
            }
        });
        jPanel1.add(jSculpture, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 89, 146));
        jLabel9.setText("Year:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 124, 27));

        QuantityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel1.add(QuantityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 89, 146));
        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 144, 27));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(17, 89, 146));
        jLabel11.setText("Hight:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 144, 27));

        HightText.setText("Enter hight of painting here");
        jPanel1.add(HightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 302, 34));

        WidhthText.setText("Enter width of painting here");
        jPanel1.add(WidhthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 302, 34));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(17, 89, 146));
        jLabel12.setText("Width:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 144, 27));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(17, 89, 146));
        jLabel13.setText("Description:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, 27));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 390, 54));
        jPanel1.add(ImageIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, -1, -1));

        pic.setBackground(new java.awt.Color(0, 102, 255));
        pic.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        pic.setText("Pic will show here");
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 150, 120));

        exitButton2.setBackground(new java.awt.Color(204, 204, 204));
        exitButton2.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        exitButton2.setForeground(new java.awt.Color(17, 89, 146));
        exitButton2.setText("Clear");
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 710, 101, 30));

        backButton1.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        backButton1.setForeground(new java.awt.Color(17, 89, 146));
        backButton1.setText("< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, -1, 30));

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        saveButton.setForeground(new java.awt.Color(17, 89, 146));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 101, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);//button doesn't exist
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //button doesn't exist
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        JFileChooser upload = new JFileChooser();
        upload.setCurrentDirectory(new File(System.getProperty("user.home")));
              FileNameExtensionFilter Filter = new FileNameExtensionFilter("All Pic" , "PNG" , "jpg"  ,"jpeg" );
              upload.addChoosableFileFilter(Filter);
              int a = upload.showSaveDialog(null);
              if(a==JFileChooser.APPROVE_OPTION){
                  File f = upload.getSelectedFile();
                  String imagefile = f.getAbsolutePath();
                 pic.setIcon(ResizeImage(imagefile));
                 picPath=imagefile;
              }
              else if(a==JFileChooser.CANCEL_OPTION)
                  System.out.println("No File is Selectd ! ");
                        
    }//GEN-LAST:event_UploadButtonActionPerformed
    public ImageIcon ResizeImage(String imgpath){
    ImageIcon myimg=new ImageIcon(imgpath);
    Image img=myimg.getImage();
    Image newimg=img.getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon image= new ImageIcon(newimg);
    return image;
    }
    private void TypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TypeItemStateChanged
        if (jSculpture.isSelected()){
            TextMaterial.setEditable(true);        
            HightText.setEditable(false);
            WidhthText.setEditable(false);}
        else if(Rpating.isSelected()){
         HightText.setEditable(true);
         WidhthText.setEditable(true);
         TextMaterial.setEditable(false);        
        }
    }//GEN-LAST:event_TypeItemStateChanged

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        ArtText.setText(" ");
        PriceText.setText(" ");
        YearText.setText(" ");
        TextMaterial.setText(" ");
        HightText.setText(" ");
        WidhthText.setText(" ");
        DesText.setText(" ");
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
           ArtistPage a = new ArtistPage(phonenumber);
           a.pack();
           a.setLocationRelativeTo(null);
           a.setVisible(true); 
           setVisible(false);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
      try(Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art")){
            PreparedStatement pst;
            InputStream finalPic=new FileInputStream(new File(picPath));
            if(jSculpture.isSelected())
            {pst=con.prepareStatement("INSERT INTO SCULPTURE (ARTNAME,PHONENUMBER,QUANTITY,PRICE,MADEYEAR,DESCRIPTION,MATERIAL,PIC) VALUES(?,?,?,?,?,?,?,?)");
                pst.setString(1, ArtText.getText());
                pst.setString(2, phonenumber);
                pst.setInt(3, Integer.parseInt(QuantityComboBox.getItemAt(QuantityComboBox.getSelectedIndex())));
                pst.setDouble(4, Double.parseDouble(PriceText.getText()));
                pst.setInt(5, Integer.parseInt(YearText.getText()));
                pst.setString(6, DesText.getText());
                pst.setString(7, TextMaterial.getText());
                pst.setBlob(8, finalPic);

                int i=pst.executeUpdate();
                if(i==1)
                JOptionPane.showMessageDialog(this, ArtText.getText()+" is added sucessfully ","AddArtwork ",JOptionPane.INFORMATION_MESSAGE );
                else
                JOptionPane.showMessageDialog(this, "an error happened \n sorry "+ArtText.getText()+" is not added try again please","AddArtwork ",JOptionPane.ERROR );

            }
            else if(Rpating.isSelected())
            {
                pst=con.prepareStatement("INSERT INTO PAINT (ARTNAME,PHONENUMBER,QUANTITY,PRICE,MADEYEAR,DESCRIPTION,WIDTH,HIEGHT,PIC) VALUES(?,?,?,?,?,?,?,?,?)");
                pst.setString(1, ArtText.getText());
                pst.setString(2, phonenumber);
                pst.setInt(3, Integer.parseInt(QuantityComboBox.getItemAt(QuantityComboBox.getSelectedIndex())));
                pst.setDouble(4, Double.parseDouble(PriceText.getText()));
                pst.setInt(5, Integer.parseInt(YearText.getText()));
                pst.setString(6, DesText.getText());
                pst.setDouble(7, Double.parseDouble(WidhthText.getText()));
                pst.setDouble(8, Double.parseDouble(HightText.getText()));
                pst.setBlob(9, finalPic);

                int i=pst.executeUpdate();
                if(i==1)
                JOptionPane.showMessageDialog(this, ArtText.getText()+"is added sucessfully","AddArtwork ",JOptionPane.INFORMATION_MESSAGE );
                else
                JOptionPane.showMessageDialog(this, "an error happened \n sorry "+ArtText.getText()+" is not added try again please","AddArtwork ",JOptionPane.ERROR );
            }
            else
            JOptionPane.showMessageDialog(this, "please select Paint or Sculpture","Error ",JOptionPane.ERROR_MESSAGE );
        }

        catch(SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage()+"","Error ",JOptionPane.ERROR_MESSAGE );
        }
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null,e.getMessage()+"","Error ",JOptionPane.ERROR_MESSAGE );
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage()+"","Error ",JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddArtWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddArtWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddArtWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddArtWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               AddArtWork a = new AddArtWork("");
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true); 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArtText;
    private javax.swing.JTextArea DesText;
    private javax.swing.JTextField HightText;
    private javax.swing.JLabel ImageIconLabel;
    private javax.swing.JTextField PriceText;
    private javax.swing.JComboBox<String> QuantityComboBox;
    private javax.swing.JRadioButton Rpating;
    private javax.swing.JTextField TextMaterial;
    private javax.swing.ButtonGroup Type;
    private javax.swing.JButton UploadButton;
    private javax.swing.JTextField WidhthText;
    private javax.swing.JTextField YearText;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jSculpture;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pic;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
