
package artvalleysystem;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author hudaalswaidan
 */

public class AdminInfo extends javax.swing.JFrame {
    public static final Pattern VALID_EMAIL_ADDRESS_REGEX =Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public static final Pattern VALID_PHONE_NUMBER = Pattern.compile("^\\s*\\d{10}");
    public static final Pattern VALID_PASSWORD =Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$*%^&+=])(?=\\S+$).{8,20}$");

    String phonenumber;
    boolean Admin=false;
    public AdminInfo(){
      initComponents();  
    }
    public AdminInfo(String phoneNumber,boolean isitAdmin) {
        super("Personal Information");
        initComponents();
        phonenumber=phoneNumber;
        Admin=isitAdmin;
        String FillQuery="";
    try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY)
             ){
            
            if(isitAdmin)
             FillQuery="select name,phonenumber,email,pass from admin where phonenumber = '"+phonenumber+"'";
            else 
             FillQuery="select name,phonenumber,email,pass from customer where phonenumber ='"+phonenumber+"'";
            
            ResultSet rs=pst.executeQuery(FillQuery);
            if(rs.first())
            { name.setText(rs.getString("name"));
            phone.setText(rs.getString("phonenumber"));
            email.setText(rs.getString("email"));
            pass1.setText(decrypt(rs.getString("pass")));
            
            rs.close();}
            else
                throw new SQLException("sorry the data aren't uploaded");            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );
            if(Admin)
            { Admin a = new Admin(phonenumber);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
                setVisible(false);}
            else
            {CustomerGui c = new CustomerGui(phonenumber);
                c.pack();
                c.setLocationRelativeTo(null);
                c.setVisible(true);
                setVisible(false);}
        }
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        exitButton1 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        exitButton.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 89, 146), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 66, -1, 70));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 89, 146));
        jLabel2.setText("Phone number:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 27));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 89, 146));
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 27));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 89, 146));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 124, 27));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 89, 146));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 27));

        name.setEditable(false);
        name.setText("Enter name here");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 293, 34));

        phone.setEditable(false);
        phone.setText("Enter number here");
        phone.setMinimumSize(new java.awt.Dimension(10, 34));
        phone.setPreferredSize(new java.awt.Dimension(80, 34));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 293, -1));

        email.setEditable(false);
        email.setText("Enter email here");
        email.setMinimumSize(new java.awt.Dimension(10, 34));
        email.setPreferredSize(new java.awt.Dimension(80, 34));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 293, -1));

        pass1.setEditable(false);
        pass1.setText("password");
        pass1.setMinimumSize(new java.awt.Dimension(10, 34));
        pass1.setPreferredSize(new java.awt.Dimension(74, 34));
        jPanel1.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 293, 35));

        exitButton1.setBackground(new java.awt.Color(0, 0, 0));
        exitButton1.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(17, 89, 146));
        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 101, 44));

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        saveButton.setForeground(new java.awt.Color(17, 89, 146));
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 101, 44));

        updateBox.setFont(new java.awt.Font("Sukar", 0, 16)); // NOI18N
        updateBox.setText("Do you want to update anything?");
        updateBox.setOpaque(false);
        updateBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateBoxStateChanged(evt);
            }
        });
        jPanel1.add(updateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("My Personal Information");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        backButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(17, 89, 146));
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 54));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/14.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Doesn't exist
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Doesn't exist
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void updateBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateBoxStateChanged
        boolean f=false;
        if(updateBox.isSelected())
            f=true;//make all componenets editable& enabled
        
        name.setEditable(f);
        phone.setEditable(f);
        email.setEditable(f);
        pass1.setEditable(f);
        saveButton.setEnabled(f);
        
    }//GEN-LAST:event_updateBoxStateChanged

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if(Admin)
            {
                Admin a = new Admin(phonenumber); 
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
                setVisible(false);
            }
            else
            {
                CustomerGui c =new CustomerGui(phonenumber);
                c.pack();
                c.setLocationRelativeTo(null);
                c.setVisible(true);       
                setVisible(false);}

    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String qu;
        
        if(!VALID_EMAIL_ADDRESS_REGEX.matcher(email.getText()).find())
             JOptionPane.showMessageDialog(null, "Inavlid Email","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(!VALID_PHONE_NUMBER.matcher(phone.getText()).find())
             JOptionPane.showMessageDialog(null, "Inavlid phone number","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(!VALID_PASSWORD.matcher(String.valueOf(pass1.getPassword())).find())
             JOptionPane.showMessageDialog(null, "Inavlid password","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(name.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Name can't be empty","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else//all valid
        {try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY)
             ){
            
            if(Admin)
                qu="update admin set name='"+name.getText()+"', phonenumber='"+phone.getText()+"',email='"+email.getText()+"',pass='"+encrypt(pass1.getText())+"' where phonenumber='"+phonenumber+"'";
            else
                qu="update customer set name='"+name.getText()+"', phonenumber='"+phone.getText()+"',email='"+email.getText()+"',pass='"+encrypt(pass1.getText())+"' where phonenumber='"+phonenumber+"'";
            System.out.println(qu);
        int i=pst.executeUpdate(qu);
        
        if(i==1)
         if(Admin)
          {Admin a = new Admin(phone.getText()); 
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
                setVisible(false);}
         else
          {CustomerGui c =new CustomerGui(phone.getText());
                c.pack();
                c.setLocationRelativeTo(null);
                c.setVisible(true);       
                setVisible(false);} 
        
        }
        catch(SQLException e){
        e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(),"Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );}
        }
            
    }//GEN-LAST:event_saveButtonActionPerformed
     public  String encrypt(String s1) {
  StringBuffer sb=new StringBuffer();
  for(int i=0;i<s1.length();i++){
   char c=s1.charAt(i);
   if(i%2==0){
    if(c==122)// if z make it a
     c=(char) 97;
    else{
     c=(char) (c+1);}}
   else{
    if(c==97)// if a make it z
     c=(char) 122;
    else
     c=(char) (c-1);}

sb.append(c);}
return sb.toString();
} 
     public String decrypt(String s1){
    StringBuffer sb=new StringBuffer();
    for(int i=0;i<s1.length();i++){
    char c=s1.charAt(i);
    if(i%2==0){
        if(c==97)
            c=(char)122;
        else
            c=(char)(c-1);}
    else{
        if(c==122)// z make it a
        c=(char) (c-25);
       else
        c=(char) (c+1);}
     sb.append(c);
    }
    return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminInfo a = new AdminInfo("",false); 
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true);       
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField email;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JTextField phone;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox updateBox;
    // End of variables declaration//GEN-END:variables
}
