
package artvalleysystem;

public class ArtistPage extends javax.swing.JFrame {
    
  String phonenumber;
    
    public ArtistPage(String p) {
        super("Artsit home page");
        initComponents();   
       phonenumber=p;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ShowratingButton = new javax.swing.JButton();
        PersoanlinfoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 89, 146));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/10.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(45, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(45, 44));
        jLabel1.setPreferredSize(new java.awt.Dimension(45, 44));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 297, 282));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 651, -1, 61));

        AddButton.setBackground(new java.awt.Color(255, 255, 255));
        AddButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        AddButton.setText("Add Artwork");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 323, 49));

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        DeleteButton.setText("Delete Artwork");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 323, 49));

        ShowratingButton.setBackground(new java.awt.Color(255, 255, 255));
        ShowratingButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        ShowratingButton.setText("Show Artwork");
        ShowratingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowratingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ShowratingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 323, 49));

        PersoanlinfoButton.setBackground(new java.awt.Color(255, 255, 255));
        PersoanlinfoButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        PersoanlinfoButton.setText("Personal Information");
        PersoanlinfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersoanlinfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PersoanlinfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 323, 50));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 651, -1, 52));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/15.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, 45));

        LogOutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogOutButton.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 40));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome Artist");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowratingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowratingButtonActionPerformed
        ShowArtwork s = new ShowArtwork(phonenumber);
        s.pack();
        s.setLocationRelativeTo(null);
        s.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_ShowratingButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        DeleteArtWork d = new DeleteArtWork(phonenumber);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        AddArtWork a = new AddArtWork(phonenumber);
        a.pack();
        a.setLocationRelativeTo(null);
        a.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
            SignIn s = new SignIn();
            s.pack();
            s.setLocationRelativeTo(null);
            s.setVisible(true); 
            setVisible(false);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void PersoanlinfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersoanlinfoButtonActionPerformed
        // TODO add your handling code here:
        PersonalInfoArtist p = new PersonalInfoArtist(phonenumber);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_PersoanlinfoButtonActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ArtistPage a = new ArtistPage("");
                a.pack();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton PersoanlinfoButton;
    private javax.swing.JButton ShowratingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
