/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package artvalleysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class DeleteArtist extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement ps ;
    
    public static final Pattern VALID_PHONE_NUMBER = Pattern.compile("^\\s*\\d{10}");
    
    Connection ConnecrDb(){
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art" );
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
         }
        return null;
    }
    String phonenumber;
    
    public DeleteArtist() {
        initComponents();
        ConnecrDb();
        UpdateTable();
        
    }  
    public DeleteArtist(String phonenumber) {
        super("Delete Artist");
        initComponents();
        ConnecrDb();
        UpdateTable();
        this.phonenumber = phonenumber;         
    }  
     
private void UpdateTable(){
    try{   
    String sql = "SELECT Name,PhoneNumber,Email,Bdate,typeOfArt, UserName FROM ARTIST";
    ps = con.prepareStatement(sql);
    rs = ps.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));}
    
    catch(SQLException ex){JOptionPane.showMessageDialog(null, ex.getMessage()); }
    catch(Exception ex){JOptionPane.showMessageDialog(null, ex.getMessage()); }
    
    finally{
        try {rs.close();
            ps.close();} 
        catch (SQLException ex) {JOptionPane.showMessageDialog(null, ex.getMessage());}
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 89, 146), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 14, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 28)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/customer.png"))); // NOI18N
        jLabel7.setText(" Deleting Artist");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 304, 250, -1));

        backButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(17, 89, 146));
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 23, -1, 40));

        jLabel1.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 89, 146));
        jLabel1.setText("Enter the Phonenumber of the artist you want to delete:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 374, 395, -1));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("e.g 0xxxxxxxxx");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 404, 395, 44));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 532, -1, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/16.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 579, -1, 61));

        deleteButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteButton.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(17, 89, 146));
        deleteButton.setText("Delete Artist");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 532, -1, -1));

        exitButton1.setBackground(new java.awt.Color(204, 204, 204));
        exitButton1.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(17, 89, 146));
        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 532, 143, -1));

        jTable1.setFont(new java.awt.Font("Sukar", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "phonenum", "pass", "email", "bdate", "typeofart", "username"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 454, -1, 72));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

            try {con.close();} 
            catch (SQLException ex) {JOptionPane.showMessageDialog(null, ex.getMessage()); }
            
            Admin d = new Admin(phonenumber);
            d.pack();
            d.setLocationRelativeTo(null);
            d.setVisible(true);
            setVisible(false);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
       // System.exit(0);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
           
       if (!VALID_PHONE_NUMBER.matcher(jTextField1.getText()).find()){
             JOptionPane.showMessageDialog(null, "Inavlid phone number","Wrong Entry" ,JOptionPane.ERROR_MESSAGE );
             jTextField1.setText("e.g 0xxxxxxxxx");}
       else{
          try{
            int ans =JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected artist?","Deleting Artist",JOptionPane.YES_NO_OPTION);
            if (ans == JOptionPane.YES_OPTION){
               String sql = "DELETE FROM ARTIST WHERE PhoneNumber=?";
               ps = con.prepareStatement(sql);
               ps.setString(1, jTextField1.getText());
               int i = ps.executeUpdate();
               if (i==1){
                 JOptionPane.showMessageDialog(null,"Artist has been deleted..");}
               else
                 {JOptionPane.showMessageDialog(null,"The phonenumber does not exist..");
                  jTextField1.setText("e.g 0xxxxxxxxx");}
            
               UpdateTable();
            }       
            else
            jTextField1.setText("e.g 0xxxxxxxxx");
           }       
         catch(SQLException ex){
             JOptionPane.showMessageDialog(null, ex.getMessage());}
         catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());}
          
        finally{
            try {
              rs.close();
               ps.close();}
            catch (SQLException ex) {JOptionPane.showMessageDialog(null, ex.getMessage());} 
        }
       }
    }//GEN-LAST:event_deleteButtonActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {   
             
              
            DeleteArtist d = new DeleteArtist();
            d.pack();
            d.setLocationRelativeTo(null);
            d.setVisible(true);
            //new DeleteArtist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
   
}
