package artvalleysystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class DeleteArt extends javax.swing.JFrame {

    private Connection connection;
    private ResultSet rs;
    private PreparedStatement ps ;
    
    
Connection ConnecrDb(){
        try{
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
        }
        catch(SQLException ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
         }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
         }
        return null;
    }

private void TableS(){    
    try{
        
    String sql = "SELECT ArtName, PhoneNumber, Quantity , Price, madeYear, Material FROM SCULPTURE";
    ps = connection.prepareStatement(sql);
    rs = ps.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(SQLException ex){
            
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
   }
    catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
    }
    finally{
            try {
            rs.close();
            ps.close();
            }
            catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
}
  
private void TableP(){
    try{
       
    String sql = "SELECT ArtName, PhoneNumber, Quantity , Price, madeYear,  colorType FROM PAINT";
    ps = connection.prepareStatement(sql);
    rs = ps.executeQuery();
    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(SQLException ex){
            
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
    }
         catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
    }
    finally{
            try {
            rs.close();
            ps.close();
            }
            catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
}
    
String phonenumber;
             
    public DeleteArt(String p) {
        super("Delete Art");
        initComponents();
        ConnecrDb();        
        phonenumber=p;

    }
    
    public DeleteArt() {
        initComponents();
        ConnecrDb();       
    }
    
    private void close() {
        try{
            connection.close();
        }
        catch(SQLException ex){
            
           JOptionPane.showMessageDialog(null, ex.getMessage()); 
        }
    } 
    public boolean isCellEditable(int row, int col)
    {return false;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        Rpainting = new javax.swing.JRadioButton();
        RSculpture = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 89, 146), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 17, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 89, 146));
        jLabel1.setText("Name:");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 60, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("e.g. BlackBird");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 352, 43));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 552, -1, 80));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 28)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/Artwork.png"))); // NOI18N
        jLabel7.setText(" Deleting ArtWork");
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 310, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/small.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, -1, 50));

        exitButton1.setBackground(new java.awt.Color(204, 204, 204));
        exitButton1.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(17, 89, 146));
        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 143, -1));

        deleteButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteButton.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(17, 89, 146));
        deleteButton.setText("Delete Art");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        Rpainting.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Rpainting);
        Rpainting.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Rpainting.setText("Painting");
        Rpainting.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RpaintingItemStateChanged(evt);
            }
        });
        jPanel1.add(Rpainting, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        RSculpture.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(RSculpture);
        RSculpture.setFont(new java.awt.Font("Sukar", 0, 16)); // NOI18N
        RSculpture.setText("Sculpture");
        RSculpture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RSculptureItemStateChanged(evt);
            }
        });
        jPanel1.add(RSculpture, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jTable1.setFont(new java.awt.Font("Sukar", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ArtName", "PhoneNumber", "Price", "Year", "Material"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 490, 80));

        jTable2.setFont(new java.awt.Font("Sukar", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 51, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Art Name", "Phonenumber", "Quantity", "Price", "Year", "Description", "ColorType", "Width", "Height"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 490, 80));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("e.g. 05xxxxxxxx");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 350, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 89, 146));
        jLabel6.setText("PhoneNumber:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
       Admin d = new Admin(phonenumber);
         d.pack();
         d.setLocationRelativeTo(null);
         d.setVisible(true);
         setVisible(false);
         close();
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

            try{
                ConnecrDb();
                int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to"
                + " delete the selected artwork?","Deleting Artwork",JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION){
            if (RSculpture.isSelected()){   
            String sql = "DELETE FROM SCULPTURE WHERE ArtName=? AND PHONENUMBER=?";
            ps = connection.prepareStatement(sql);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, jTextField2.getText());
            int i = ps.executeUpdate();
            if (i==1){
            JOptionPane.showMessageDialog(null,"ArtWork has been deleted..");}            
            else
            {JOptionPane.showMessageDialog(null,"The artwork does not exist..");
             jTextField1.setText("e.g. BlackBird");
            jTextField2.setText("e.g. 05xxxxxxxxxx");}            
             TableS();
            }
            if (Rpainting.isSelected()){   
            String sql = "DELETE FROM PAINT WHERE ArtName=? AND PHONENUMBER=?";
            ps = connection.prepareStatement(sql);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, jTextField2.getText());
            int i = ps.executeUpdate();
            if (i==1){
            JOptionPane.showMessageDialog(null,"ArtWork has been deleted..");}            
            else
            {JOptionPane.showMessageDialog(null,"The artwork does not exist..");
             jTextField1.setText("e.g. BlackBird");
             jTextField2.setText("e.g. 05xxxxxxxxxx");}            
             TableP(); 
            }
            
        }       
        else
            jTextField1.setText("e.g. BlackBird");
            }
        
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());}
      
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
          
      }
      finally{
          try{
              ps.close();
              rs.close();
          }
          catch(SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
            }
      }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void RpaintingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RpaintingItemStateChanged
       
        try{  jTextField1.setText("e.g. BlackBird");
              jTable1.setVisible(false);
              TableP();
              jTable2.setVisible(true);
              
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); }
    }//GEN-LAST:event_RpaintingItemStateChanged

    private void RSculptureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RSculptureItemStateChanged
    
        try{  jTextField1.setText("e.g. BlackBird");
              jTable2.setVisible(false);
              TableS();
              jTable1.setVisible(true);
              
        }
        catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage()); }
    }//GEN-LAST:event_RSculptureItemStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        jTextField1.setText(jTable1.getModel().getValueAt(row, 0).toString());
        jTextField2.setText(jTable1.getModel().getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row=jTable2.getSelectedRow();
        jTextField1.setText(jTable2.getModel().getValueAt(row, 0).toString());
        jTextField2.setText(jTable2.getModel().getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteArt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteArt d = new DeleteArt();
                d.pack();
                d.setLocationRelativeTo(null);
                d.setVisible(true);
                //new DeleteArt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RSculpture;
    private javax.swing.JRadioButton Rpainting;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

 
}
