package artvalleysystem;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class MyOrders extends javax.swing.JFrame {
 public static ArrayList<Bill> orders=new ArrayList<>();

     String phonenumber;
    public MyOrders(String p) {
        super("My previous orders");
        phonenumber=p;
        initComponents();

    }
private void showorders(String message, JTextArea AllOrders){
     try(Connection connect= DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
        PreparedStatement pp= connect.prepareStatement("SELECT * FROM TORDER WHERE PHONENUMBER = ?"))
        {
             pp.setString(1, phonenumber);
             ResultSet rs= pp.executeQuery();

             while(rs.next())
               orders.add(new Bill(rs.getInt("ID"), rs.getInt("QUANTITY"),rs.getDouble("PRICE"), rs.getDate("ORDERDATE")));
             message=" ";
             
        }
     catch(SQLException sql){JOptionPane.showMessageDialog(this, sql.getMessage());}
     if(!orders.isEmpty())
                for(int i=0; i<orders.size(); i++){
                 message+=orders.get(i).toString()+"\n----------------------------\n";}
              
             else{ message="Sorry, you have not any order :(";}
             AllOrders.setText(message);
             AllOrders.setEditable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllOrders = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(17, 89, 147));

        jPanel1.setBackground(new java.awt.Color(17, 89, 146));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        /*if(!orders.isEmpty()){
            Box boxy= Box.createVerticalBox();
            buttons= new JTextArea[orders.size()];

            for(int i=0; i<orders.size(); i++){
                buttons[i]= new JTextArea(orders.get(i).toString(), 2, 20);
                buttons[i].setEditable(false);
                buttons[i].setEnabled(false);
                boxy.add(new JScrollPane(buttons[i]));
            }
            jPanel1.add(boxy);}else{ empty= new JLabel("You have not any order:(");
            jPanel1.add(empty);
        }*/

        jLabel2.setFont(new java.awt.Font("Sukar", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Previous Orders");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        backButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(17, 89, 146));
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/4s.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 260, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/3s.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, 220));

        AllOrders.setFont(new java.awt.Font("Sukar", 0, 18));
        AllOrders.setColumns(20);
        AllOrders.setForeground(new java.awt.Color(0, 51, 102));
        AllOrders.setRows(5);
        String msg="";
        showorders(msg,AllOrders );
        jScrollPane2.setViewportView(AllOrders);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 440, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CustomerGui c= new CustomerGui(phonenumber);
            c.pack();
            c.setLocationRelativeTo(null);
            c.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Artvalley","art","art")){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // MyOrders o = new MyOrders("");
                //o.pack();
               // o.setLocationRelativeTo(null);
               // o.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AllOrders;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
