package artvalleysystem;


import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;


public class Paintings extends javax.swing.JFrame {


    String phonenumber;

    String DefaultQuery="select pic,artname,price,madeYear,description,username from paint,artist where artist.phonenumber=paint.phonenumber and Quantity>0";
    String LikeQuery="select pic,artname,price,madeYear,description,username from paint,artist where artist.phonenumber=paint.phonenumber and Quantity>0 and artname like '%";
    public Paintings(String p) {
        initComponents();
        phonenumber=p;
        fillTable();

    }


    private void fillTable(){

        try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(DefaultQuery))
        { fromResultSetToTable(rs);}
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        Searchtext = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paintings");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Sukar", 1, 17)); // NOI18N
        backButton.setForeground(new java.awt.Color(17, 89, 146));
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));
        jPanel1.add(Searchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 320, -1));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Picture", "name", "Price", "Artist Username", "Made year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/pp.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CustomerGui c = new CustomerGui(phonenumber);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
        String ArtName=jTable1.getModel().getValueAt(row, 1).toString();
        String ArtistUsername=jTable1.getModel().getValueAt(row, 3).toString();
        new AddToCart(phonenumber,ArtistUsername,ArtName).setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
       if(Searchtext.getText().equals(""))
         fillTable();
       
       else{   
        try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(LikeQuery+Searchtext.getText()+"%'"))
            {fromResultSetToTable(rs);}
        
        catch(SQLException e){JOptionPane.showMessageDialog(this, e.getMessage());}
       }
    }//GEN-LAST:event_SearchActionPerformed

    private void fromResultSetToTable(ResultSet rs) throws SQLException{
        boolean isRsHaveValue=false;
        Pa ob;
        ArrayList<Pa> list=new ArrayList();
            while(rs.next()){
            isRsHaveValue=true;
            ob=new Pa(rs.getString("artname"),rs.getInt("madeyear"),rs.getDouble("price"),rs.getString("username"),rs.getBytes("pic"));
            list.add(ob);}
            if(!isRsHaveValue)
       {JOptionPane.showMessageDialog(this, "Sorry there's no painting right now\nif you have searched try searching without keywords","No paintings",JOptionPane.INFORMATION_MESSAGE);}
        String[] columnName = {"Picture","Name","Price","Username","Made year"};
        Object[][] rows = new Object[list.size()][5];
        
        for(int i = 0; i < list.size(); i++){
            if(list.get(i).Image != null){
            ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).Image).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH) );   
            rows[i][0] = image;
            }
            else
                rows[i][0] = null;
                
            rows[i][1] = list.get(i).name;
            rows[i][2] = list.get(i).price;
            rows[i][3] = list.get(i).username;
            rows[i][4] = list.get(i).year;

        }
        
        TheModel model = new TheModel(rows, columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        //set size of table
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(170);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
        //set table header names
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Picture");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Name");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Price");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Artist Username");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("Made year");
        //set left Alignment
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(leftRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(leftRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(leftRenderer);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paintings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paintings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paintings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paintings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             Paintings p = new Paintings("");
                p.pack();
                p.setLocationRelativeTo(null);
                p.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JTextField Searchtext;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}


 class Pa {

     String name;
     int year;
     double price;
     String username;
     byte[] Image;

    public Pa(String name, int year, double price, String username, byte[] Image) {
        this.name = name;
        this.year = year;
        this.price = price;
        this.username = username;
        this.Image = Image;
    }
 
}
 class TheModel extends AbstractTableModel {

    private String[] columns;
    private Object[][] rows;

    
    public TheModel(Object[][] data, String[] columnName){
        this.rows = data;
        this.columns = columnName;
    }
    @Override
    public Class getColumnClass(int column){
        if(column == 0)return Icon.class;
        else {//System.out.println(column+" is "+getValueAt(0,column).getClass());
        return getValueAt(0,column).getClass();}
    }
    @Override
    public int getRowCount() {return this.rows.length;}

    @Override
    public int getColumnCount() {return this.columns.length;}

    @Override
    public Object getValueAt(int i, int i1) {return this.rows[i][i1];}
}
