package artvalleysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class PersonalInfoArtist extends javax.swing.JFrame {
public Artist a= new Artist(); //we don't use it but its in uneditable code

 public static final Pattern VALID_EMAIL_ADDRESS_REGEX =Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public static final Pattern VALID_PHONE_NUMBER = Pattern.compile("^\\s*\\d{10}");
    public static final Pattern VALID_PASSWORD =Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$*%^&+=])(?=\\S+$).{8,20}$");
     String phonenumber;
    public PersonalInfoArtist(String p) {
        super("Personal information");
        initComponents();
        phonenumber=p;
        try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY)
             ){
            ResultSet rs=pst.executeQuery("select name,phonenumber,email,pass,typeofart,username from artist where phonenumber = '"+phonenumber+"'");
            if(rs.first())
                { namefield.setText(rs.getString("name"));
                  phonefield.setText(rs.getString("phonenumber"));
                  emailfield.setText(rs.getString("email"));
                  passvalid.setText(decrypt(rs.getString("pass")));
                  usernamefield.setText(rs.getString("username"));
                  typefield.setText(rs.getString("typeofart"));
                  rs.close();}
            else
                  throw new SQLException("Sorry the data aren't uploaded");
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.getMessage(),"Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );}
    }

    public  String encrypt(String s1) {
  StringBuffer sb=new StringBuffer();
  for(int i=0;i<s1.length();i++){
   char c=s1.charAt(i);
   if(i%2==0){
    if(c==122)
     c=(char) 97;
    else{
     c=(char) (c+1);}}
   else{
    if(c==97)
     c=(char) 122;
    else
     c=(char) (c-1);}

sb.append(c);}
return sb.toString();
} 
     public String decrypt(String s1){
    StringBuffer sb=new StringBuffer();
    for(int i=0;i<s1.length();i++){
    char c=s1.charAt(i);
    if(i%2==0){
        if(c==97)
            c=(char)122;
        else
            c=(char)(c-1);}
    else{
        if(c==122)
        c=(char) (c-25);
       else
        c=(char) (c+1);}
     sb.append(c);
    }
    return sb.toString();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        usernamefield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        updateBox = new javax.swing.JCheckBox();
        passvalid = new javax.swing.JPasswordField();
        save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        typefield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Artist's Information");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 89, 146), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 89, 146));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 89, 146));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 89, 146));
        jLabel4.setText("Phone number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 89, 146));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        namefield.setEditable(false);
        namefield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        namefield.setText(a.name);
        jPanel1.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, 30));

        usernamefield.setEditable(false);
        usernamefield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 300, 30));

        phonefield.setEditable(false);
        phonefield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 300, 30));

        updateBox.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        updateBox.setText("You want to update anything?");
        updateBox.setOpaque(false);
        updateBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateBoxStateChanged(evt);
            }
        });
        jPanel1.add(updateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        passvalid.setEditable(false);
        passvalid.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(passvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 300, 30));

        save.setFont(new java.awt.Font("Sukar", 1, 20)); // NOI18N
        save.setForeground(new java.awt.Color(17, 89, 146));
        save.setText("Save");
        save.setEnabled(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 130, 40));

        jLabel6.setFont(new java.awt.Font("Sukar", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("My Personal Information");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 54));

        jLabel9.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 89, 146));
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        backButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(17, 89, 146));
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 520, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/14.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, 260));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 390, 54));

        emailfield.setEditable(false);
        emailfield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 300, 30));

        typefield.setEditable(false);
        typefield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jPanel1.add(typefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 300, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(17, 89, 146));
        jLabel7.setText("Type of art:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateBoxStateChanged
        boolean f=false;
        if(updateBox.isSelected())
            f=true;//make all componenets editable& enabled
        
        namefield.setEditable(f);
        phonefield.setEditable(f);
        emailfield.setEditable(f);
        passvalid.setEditable(f);
        usernamefield.setEditable(f);
        typefield.setEditable(f);
        save.setEnabled(f);
    }//GEN-LAST:event_updateBoxStateChanged

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(!VALID_EMAIL_ADDRESS_REGEX.matcher(emailfield.getText()).find())
             JOptionPane.showMessageDialog(null, "Inavlid Email","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(!VALID_PHONE_NUMBER.matcher(phonefield.getText()).find())
             JOptionPane.showMessageDialog(null, "Inavlid phone number","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(!VALID_PASSWORD.matcher(String.valueOf(passvalid.getPassword())).find())
             JOptionPane.showMessageDialog(null, "Inavlid password","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else if(namefield.getText().equals("")||usernamefield.getText().equals("")||typefield.getText().equals(""))
            JOptionPane.showMessageDialog(null, "you must fill name ,username ,and type of art","Personal information" ,JOptionPane.ERROR_MESSAGE );
        else//all valid
        {
            try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY)
             ){
              int i=pst.executeUpdate("update artist set name='"+namefield.getText()+"', phonenumber='"+phonefield.getText()+"',email='"+emailfield.getText()+"',pass='"+encrypt(passvalid.getText())+"',username='"+usernamefield.getText()+"',typeofart='"+typefield.getText()+"' where phonenumber='"+phonenumber+"'");
              if(i==1)
                {ArtistPage s = new ArtistPage(phonenumber);
                s.pack();
                s.setLocationRelativeTo(null);
                s.setVisible(true); 
                setVisible(false);} 
              }
           catch(SQLException e){JOptionPane.showMessageDialog(null, e.getMessage(),"Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );}
        }
    }//GEN-LAST:event_saveActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ArtistPage s = new ArtistPage(phonenumber);
        s.pack();
        s.setLocationRelativeTo(null);
        s.setVisible(true); 
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInfoArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInfoArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInfoArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInfoArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonalInfoArtist p = new PersonalInfoArtist("");
                p.pack();
                p.setLocationRelativeTo(null);
                p.setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField passvalid;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton save;
    private javax.swing.JTextField typefield;
    private javax.swing.JCheckBox updateBox;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
