package artvalleysystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class SavedAddress extends javax.swing.JFrame {

    String phoneNumber;
    public SavedAddress(String p) {
        super("Saved address");
        initComponents();
        phoneNumber=p;
        intilaize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        streetfield = new javax.swing.JTextField();
        anfield = new javax.swing.JTextField();
        Update = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        city = new javax.swing.JComboBox<>();
        ZIPCode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Addresses");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 89, 146));
        jLabel2.setText("City:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 89, 146));
        jLabel3.setText("Additional Number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(17, 89, 146));
        jLabel4.setText("Street:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 89, 146));
        jLabel5.setText("Zip Code:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        exitButton.setBackground(new java.awt.Color(204, 204, 204));
        exitButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 51, 102));
        exitButton.setText("Back");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 90, 40));

        saveButton.setBackground(new java.awt.Color(204, 204, 204));
        saveButton.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 51, 102));
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 90, 40));

        streetfield.setEditable(false);
        streetfield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        streetfield.setForeground(new java.awt.Color(17, 89, 146));
        jPanel1.add(streetfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 230, 40));

        anfield.setEditable(false);
        anfield.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        anfield.setForeground(new java.awt.Color(17, 89, 146));
        jPanel1.add(anfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 230, 40));

        Update.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        Update.setText("Do you want to edit your address?");
        Update.setOpaque(false);
        Update.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                UpdateStateChanged(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/artvalleysystem/12.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 54));

        jLabel7.setFont(new java.awt.Font("Sukar", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Saved Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        city.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        city.setForeground(new java.awt.Color(17, 89, 146));
        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Riyadh\t", "Zulfi\t", "Makkah\t", "Madinah\t", "Jeddah\t", "Taif\t", "Yunbu\t", "Dammam\t", "Ras Tanura\t", "Jubail Industrial\t", "Khobar\t", "Dhahran\t", "Hafr Al-Batin\t", "Badr\t", "Tabuk\t", "Amlaj\t", "Wadi as Surr\t", "Buraidah\t", "Unaizah\t", "Ha'il\t", "Abha\t", "Al Bahah\t", "Khamis Mmushait\t", "Najran\t", "Sakaka\t", "Turaif\t", "Rafha\t", "Al Qurayyar\t", "Al Qurayyat\t", "Jizan\t", "Aaar\t", "Jubai\t", "Hail\t", "Rabigh\t", "Taif\t", "Bahah\t", "Hofuf\t", "Dhahran\t", "Tayma\t", "Yanbu\t", "Haradh" }));
        city.setEnabled(false);
        city.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityItemStateChanged(evt);
            }
        });
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 230, 40));

        ZIPCode.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        ZIPCode.setForeground(new java.awt.Color(17, 89, 146));
        ZIPCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11564", "15941", "24230", "20012", "21577", "26513", "30799", "32241", "32816", "35541", "34424", "34464", "39923", "46357", "47711", "48313", "49549", "51431", "51911", "55425", "61321", "65525", "61961", "61441", "75471", "75311", "76321", "77425", "77451", "88723", "73311", "35412", "55211", "25725", "26312", "65511", "36362", "32225", "45511", "46424", "36699" }));
        ZIPCode.setSelectedIndex(-1);
        ZIPCode.setEnabled(false);
        jPanel1.add(ZIPCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        CustomerGui c = new CustomerGui(phoneNumber);
        c.pack();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void UpdateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_UpdateStateChanged
        boolean f=false;
        if(Update.isSelected())
            f=true;
        
        city.setEnabled(f);
        streetfield.setEditable(f);
        anfield.setEditable(f);
        saveButton.setEnabled(f);
 
    }//GEN-LAST:event_UpdateStateChanged

    private void cityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityItemStateChanged
        ZIPCode.setSelectedIndex(city.getSelectedIndex());
    }//GEN-LAST:event_cityItemStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art");
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY))
            {String query="UPDATE CUSTOMER SET CITY='"+city.getItemAt(city.getSelectedIndex())+"', ZIPCODE="+Integer.parseInt(ZIPCode.getItemAt(ZIPCode.getSelectedIndex()))+", STREET='"+streetfield.getText()+"' ,ADDNUM="+Integer.parseInt(anfield.getText())+" WHERE PHONENUMBER='"+phoneNumber+"'";
             int i=pst.executeUpdate(query);
             if(i==1)
              {JOptionPane.showMessageDialog(null, "your addres have been updated","Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );
               intilaize();}
            }
        catch(SQLException e){JOptionPane.showMessageDialog(null, e.getMessage(),"Address" ,JOptionPane.ERROR_MESSAGE );}
    }//GEN-LAST:event_saveButtonActionPerformed

    private void intilaize(){
         try(Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/sampleForArtvalley","art","art"); 
            Statement pst=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=pst.executeQuery("select city,street,addnum from customer where phonenumber='"+phoneNumber+"'")){
            if(rs.next())
              {String c=rs.getString("city");
              streetfield.setText(rs.getString("street"));
              anfield.setText(String.valueOf(rs.getInt("addnum")));
              for(int i=0;i<city.getItemCount();i++)
                  if(city.getItemAt(i).equalsIgnoreCase(c))
                  {city.setSelectedIndex(i);
                  ZIPCode.setSelectedIndex(i);
                  break;}
            }
            else throw new SQLException("sorry data aren't uploaded");
            
        }
        catch(SQLException e){
         JOptionPane.showMessageDialog(null, e.getMessage(),"Personal Infotmation" ,JOptionPane.ERROR_MESSAGE );}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavedAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavedAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavedAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavedAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               SavedAddress s = new SavedAddress("");
                s.pack();
                s.setLocationRelativeTo(null);
                s.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Update;
    private javax.swing.JComboBox<String> ZIPCode;
    private javax.swing.JTextField anfield;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField streetfield;
    // End of variables declaration//GEN-END:variables
}
